version: "3.8"
services:
  postgres-savecoupon-db:
    image: postgres:latest
    container_name: postgres_savecoupon_container
    environment:
      POSTGRES_DB: rabitmq_saved
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "9207400638" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  
    volumes:
      - .:/app
    container_name: savecoupon_container
    ports:
      - 8003:8003
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8003 savecoupon.wsgi:application"
    environment:
      DB_HOST: postgres-savecoupon-db
      DB_NAME: rabitmq_saved
      DB_USER: postgres
      DB_PASSWORD: "9207400638"  
    depends_on:
      - postgres-savecoupon-db

volumes:
  postgres_data:
