version: "3.8"
services:
  postgres-couponbackup-db:
    image: postgres:latest
    container_name: postgres_couponbackup_container
    environment:
      POSTGRES_DB: coupon_backup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "9207400638" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  
    volumes:
      - .:/app
    container_name: couponbackup_container
    ports:
      - 8001:8001
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8001 couponbackup.wsgi:application"
    environment:
      DB_HOST: postgres-couponbackup-db
      DB_NAME: coupon_backup
      DB_USER: postgres
      DB_PASSWORD: "9207400638"  
    depends_on:
      - postgres-couponbackup-db

volumes:
  postgres_data:
