# Generated by Django 5.0.4 on 2024-04-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_product_id_alter_product_coupouncode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='coupouncode',
            new_name='couponcode',
        ),
    ]
