version: "3.8"
services:
  postgres-couponmain-db:
    image: postgres:latest
    container_name: postgres_couponmain_container
    environment:
      POSTGRES_DB: rabitmq_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "9207400638" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  
    volumes:
      - .:/app
    container_name: couponmain_container
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 couponmain.wsgi:application"
    environment:
      DB_HOST: postgres-couponmain-db
      DB_NAME: rabitmq_products
      DB_USER: postgres
      DB_PASSWORD: "9207400638"  
    depends_on:
      - postgres-couponmain-db

volumes:
  postgres_data:
