version: "3.8"
services:
  postgres-redeemservice-db:
    image: postgres:latest
    container_name: postgres_redeemservice_container
    environment:
      POSTGRES_DB: rabitmq_redeem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "9207400638" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  
    volumes:
      - .:/app
    container_name: redeemservice_container
    ports:
      - 8002:8002
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8002 redeemservice.wsgi:application"
    environment:
      DB_HOST: postgres-redeemservice-db
      DB_NAME: rabitmq_redeem
      DB_USER: postgres
      DB_PASSWORD: "9207400638"  
    depends_on:
      - postgres-redeemservice-db

volumes:
  postgres_data:
